version: 2.1

aliases:
  - &only-dev-branch
    branches:
      only: dev

jobs:
  plan:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:0.15.3

    steps:
      - checkout
      - run:
          name: terraform init
          command: |
            echo "export TERRAFORM_STATE_BUCKET=$TERRAFORM_STATE_BUCKET" >> $BASH_ENV
            echo "export TERRAFORM_STATE_KEY=$TERRAFORM_STATE_KEY" >> $BASH_ENV
            echo "export TERRAFORM_STATE_REGION=$TERRAFORM_STATE_REGION" >> $BASH_ENV
            "set -x;terraform init -backend-config=bucket=$TERRAFORM_STATE_BUCKET -backend-config=key=$TERRAFORM_STATE_KEY -backend-config=region=$TERRAFORM_STATE_REGION"
      - run: terraform workspace select dev || terraform workspace new dev
      - run: echo "export TF_VAR_slack_channels=[$SLACK_CHANNEL]" >> $BASH_ENV
      - run: echo "export TF_VAR_slack_channels_dev=[$SLACK_CHANNEL_DEV]" >> $BASH_ENV
      - run: echo "export TF_VAR_slack_webhook_urls=[$SLACK_WEBHOOK_URL]" >> $BASH_ENV
      - run: terraform plan -out tfplan
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  cd:
    jobs:
      - plan:
          filters: *only-dev-branch