version: 2.1

aliases:
  - &only-dev-branch
    branches:
      only: dev

jobs:
  init:
    docker:
      - image: hashicorp/terraform:0.15.3

    steps:
      - checkout
      - run: echo "export INIT_ARGS=$INIT_ARGS" >> $BASH_ENV
      - run:
          command: "set -x;terraform init $INIT_ARGS"

workflows:
  cd:
    jobs:
      - init:
          filters: *only-dev-branch